### ISSUE TITLE
package.json 里的 version 与已发布的版本不一致导致难以溯源

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/fc3#10]
package.json 中记录的 version 为 1.0.0 
https://github.com/devsapp/fc3/blob/2ceb97c3521db2d5f045c07def6c7ac322ef3e8b/package.json#L3

但 https://github.com/devsapp/fc3/releases 中最新的版本为 0.0.30 .

这导致本地查看 ${USER}/.s/components/devapps.cn/v3/fc3/package.json 时无法确定本地使用的 fc3 组件到底是哪个版本的.

**Comment by DevDengChao** [comment]
另外发现 ${USER}/.s/components/devapps.cn/v3/fc3/s.lock 文件似乎记录了 fc3 组件的版本号.

**Comment by rsonghuster** [comment]
已经更新
